# -*- coding: utf-8 -*-
"""Практика Отчет 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CuB3sHqaRaXzxlNXFXm334VfEb_60qWy
"""

import pandas as pd
import sqlite3
from pathlib import Path

# Читаем CSV-файл
df = pd.read_csv('SalesPlus_manager.csv', encoding='utf-8')

# Создаем временную SQLite базу данных в памяти
conn = sqlite3.connect(':memory:')

# Сохраняем данные из CSV в SQLite таблицу
df.to_sql('SalesPlus_manager', conn, index=False, if_exists='replace')

#Список всех менеджеров
query0 = """
select distinct Менеджер
from SalesPlus_manager
"""

# вносими в список менеджеров
managers_df = pd.read_sql_query(query0, conn)
managers_list = managers_df['Менеджер'].tolist()

#цикл для каждого менеджера
for manager in managers_list:
  # Запрос по каждому менеджеру
  query1 =f"""
  select 	Контрагент,
          Sum(coalesce (Итого,0)) as Итого,
          max(Category_manager) as Категория
  from SalesPlus_manager
  where Менеджер = '{manager}'
  group by Контрагент
  order by Итого desc
  """
  # Выполняем запрос
  result = pd.read_sql_query(query1, conn)
  # Создаем имя файла
  output_file = f"02 Менеджер {manager}.xlsx"
  result.to_excel(output_file, index=False)


# Закрываем соединение
conn.close()



import pandas as pd
import sqlite3

# Читаем CSV-файл
df = pd.read_csv('SalesPlus_manager.csv', encoding='utf-8')

# Создаем временную SQLite базу данных в памяти
conn = sqlite3.connect(':memory:')

# Сохраняем данные из CSV в SQLite таблицу
df.to_sql('SalesPlus_manager', conn, index=False, if_exists='replace')

# Получаем список всех менеджеров
query_managers = """
select distinct Менеджер
from SalesPlus_manager
order by Отдел, Менеджер
"""

managers_df = pd.read_sql_query(query_managers, conn)
managers_list = managers_df['Менеджер'].tolist()

# Создаем Excel файл с несколькими листами
output_file = '03 Менеджеры.xlsx'

with pd.ExcelWriter(output_file, engine='openpyxl') as writer:
    # Создаем лист для каждого менеджера с нумерацией
    for i, manager in enumerate(managers_list, 1):
        # Запрос для конкретного менеджера
        query_manager = f"""
        select 	Контрагент,
        Sum(coalesce (Итого,0)) as Итого,
        max(Category_manager) as Категория
        from SalesPlus_manager
        where Менеджер = '{manager}'
        group by Контрагент
        order by Итого desc
        """

        # Выполняем запрос
        result = pd.read_sql_query(query_manager, conn)

        # Создаем имя для листа с номером + фамилия
        short_name = manager.split()[0]  # Берем только фамилию
        sheet_name = f"{i:02d}_{short_name}"[:31]  # Ограничиваем 31 символ

        # Сохраняем на отдельном листе
        result.to_excel(writer, sheet_name=sheet_name, index=False)

        # Получаем объект листа
        worksheet = writer.sheets[sheet_name]
        # Настройка ширины столбцов
        worksheet.column_dimensions['A'].width = 45
        worksheet.column_dimensions['B'].width = 20
        worksheet.column_dimensions['C'].width = 25
# Закрываем соединение
conn.close()