# -*- coding: utf-8 -*-
"""Практика Отчет 7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lMQbqkshmTA4r5-4CU6yqwHFvve-HUmi
"""

# Формируем Эксель файл по страницам
# Одна страница - список потерянных клиентов по отделу
import pandas as pd
import sqlite3

# Читаем CSV-файл
df = pd.read_csv('Sales_cntDepartmen.csv', encoding='utf-8')

# Создаем временную SQLite базу данных в памяти
conn = sqlite3.connect(':memory:')

# Сохраняем данные из CSV в SQLite таблицу
df.to_sql('Sales_cntDepartmen', conn, index=False, if_exists='replace')

#Список всех отделов
query0 = """
select distinct Отдел
from Sales_cntDepartmen
order by Отдел
"""

# вносими в список отделов
departmen_df = pd.read_sql_query(query0, conn)
departmen_list = departmen_df['Отдел'].tolist()

# Создаем Excel файл с несколькими листами
output_file = '07 Отделы.xlsx'

with pd.ExcelWriter(output_file, engine='openpyxl') as writer:
    # Создаем лист для каждого менеджера с нумерацией
    for i, departmen in enumerate(departmen_list, 1):
        # Запрос для конкретного менеджера
        query_2 = f"""
        select Контрагент, Итого
        from Sales_cntDepartmen
        where cnt_second =0 and Отдел = '{departmen}'
        order by Итого desc
        """

        # Выполняем запрос
        result = pd.read_sql_query(query_2, conn)

        # Создаем имя для листа с номером + фамилия
        short_name = departmen.split()[0]  # Берем только фамилию
        sheet_name = f"{i:02d}_{short_name}"[:31]  # Ограничиваем 31 символ

        # Сохраняем на отдельном листе
        result.to_excel(writer, sheet_name=sheet_name, index=False)

        # Получаем объект листа
        worksheet = writer.sheets[sheet_name]
        # Настройка ширины столбцов
        worksheet.column_dimensions['A'].width = 45
        worksheet.column_dimensions['B'].width = 25

# Закрываем соединение
conn.close()

# Формируем Эксель файл по страницам
# Одна страница - список потерянных клиентов по отделу
import pandas as pd
import sqlite3

# Читаем CSV-файл
df = pd.read_csv('Sales_cntManager.csv', encoding='utf-8')

# Создаем временную SQLite базу данных в памяти
conn = sqlite3.connect(':memory:')

# Сохраняем данные из CSV в SQLite таблицу
df.to_sql('Sales_cntManager', conn, index=False, if_exists='replace')

# Получаем список всех менеджеров
query_managers = """
select distinct Менеджер
from Sales_cntManager
order by Менеджер
"""

managers_df = pd.read_sql_query(query_managers, conn)
managers_list = managers_df['Менеджер'].tolist()

# Создаем Excel файл с несколькими листами
output_file = '07 Менеджеры.xlsx'

with pd.ExcelWriter(output_file, engine='openpyxl') as writer:
    # Создаем лист для каждого менеджера с нумерацией
    for i, manager in enumerate(managers_list, 1):
        # Запрос для конкретного менеджера
        query_2 = f"""
        select Контрагент, Итого
        from sales_cntManager
        where cnt_second =0 and Менеджер = '{manager}'
        order by Итого desc
        """

        # Выполняем запрос
        result = pd.read_sql_query(query_2, conn)

        # Создаем имя для листа с номером + фамилия
        short_name = manager.split()[0]  # Берем только фамилию
        sheet_name = f"{i:02d}_{short_name}"[:31]  # Ограничиваем 31 символ

        # Сохраняем на отдельном листе
        result.to_excel(writer, sheet_name=sheet_name, index=False)

        # Получаем объект листа
        worksheet = writer.sheets[sheet_name]
        # Настройка ширины столбцов
        worksheet.column_dimensions['A'].width = 45
        worksheet.column_dimensions['B'].width = 25
# Закрываем соединение
conn.close()